### ISSUE TITLE
Common function to show and hide Modal

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#1]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/container/Dashboard.js#L26

Can we have a common function like below, to handle visibility of Modal instead of different showModal and closeModal functions?

```
toggleModal(){
       this.setState({
            showModal: !this.state.showModal
        }); 
    }
```

**Comment by JiteshKusalkar** [comment]
Done.
