### ISSUE TITLE
generateElement markup changes suggestions

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#10]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/component/Form/Form.js#L138

In most of the get form element functions `<div key={i} className="form-group row">` is common wrapper for all.

So can we have `let res = <div key={eindex} className="form-group row">` before `switch` and end of `res` will get appended with `</div>`?

**Comment by JiteshKusalkar** [comment]
That gives a multi line warning in all the component generator functions.
