### ISSUE TITLE
Column headers data at component level

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#2]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/container/Dashboard.js#L55

As this `columns` are static, can we declare them at component level in the `constructor` itself?

Something like `this.colHeaders` and pass them as props to `Table` components.

This will prevent `columns` initialization on every component render.

**Comment by JiteshKusalkar** [comment]
Done.
