### ISSUE TITLE
Table header cell

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#3]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/component/Table/Table.js#L50

Can we extract `TableHeadComponent` from render to a function, something like `getHeaderCell()` which will return markup for the header?

Same applies for `TableBodyColumn` and `TableBodyComponent`.

**Comment by ManjushaMGlobant** [comment]
Also use PropTypes for props validations.

**Comment by ManjushaMGlobant** [comment]
Instead of accessing `this.props.columns` directly you can use shorthand property like `const { columns } = this.props`

**Comment by JiteshKusalkar** [comment]
Done
