### ISSUE TITLE
Modal code changes

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#4]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/component/Modal/Modal.js#L12

1. Instead of inline element styling, better use class to apply the css in different css file.

2. It will be good if we move `ModalHeader`, `ModalBody` and `ModalFooter` into different component files.

3. In `Modal` component, can we have a function that will return markup for modal? Something like `getModal()`

**Comment by JiteshKusalkar** [comment]
Done
