### ISSUE TITLE
Input form element suggestions

### ISSUE THREAD

**Issue by ManjushaMGlobant** [sachin9890/React-App#5]
https://github.com/sachin9890/React-App/blob/1d4d6a06f0749dd1937dd7d5ea100af533050744/src/component/FormElements/Input.js#L11

1. Can we rename prop `classes` to `customClass`? Wherein props validation it will be `PropTypes.string`.

2. You can also try `className={"form-control " + this.props.classes}` if `form-control` is common class.

3. Just a suggestion to use ES6 shorthand property to get props.
`const { id, type, disabled, ...} = this.props`

**Comment by JiteshKusalkar** [comment]
Done. Gave 'form-control' as default value to the prop.

Not sure about declaring props attribute into separate constants as its increasing the memory. So I skipped it.
